sudo: no
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "2.7"

addons:
  postgresql: "9.3"

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - nosetests socorrolib

notifications:
#  webhooks: http://leeroybot.lonnen.com/hubot/travis?room=%23breakpad

# todo: deploy to pypi
#deploy:
#    provider: pypi
#    user: lonnen
#    password:
#    on:
#        repo:
#        branch: master
#distributions: "sdist bdist_wheel"
